AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# This allows for semantic exceptions
Style/RaiseArgs:
  Enabled: false

# We should embrace UTF-8, not shun it.
Style/AsciiComments:
  Enabled: false

# Explicitly returning nil in an else is sometimes more clear.
Style/EmptyElse:
  Enabled: false

# If/unless at the end of the line makes it harder to miss control flow.
Style/IfUnlessModifier:
  Enabled: false

# This doesn’t always make sense.
Style/GuardClause:
  Enabled: false

# ----- ENABLED (new) -----

# These cops are new and need to be manually enabled.

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# ----- DISABLED (tests) -----

# These cops are disabled in test cases only.

Style/Documentation:
  Exclude:
    - "test/**/*.rb"

Style/GlobalVars:
  Exclude:
    - "test/**/*.rb"

Lint/NestedMethodDefinition:
  Exclude:
    - "test/**/*.rb"

# ----- DISABLED (metrics) -----

# Cops for metrics are disabled because they should not cause tests to fail.

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
