inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Trailing commas in a multiline context makes diffs nicer.
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# This allows for semantic exceptions
Style/RaiseArgs:
  Enabled: false

# We should embrace UTF-8, not shun it.
Style/AsciiComments:
  Enabled: false

# Explicitly returning nil in an else is sometimes more clear.
Style/EmptyElse:
  Enabled: false

# If/unless at the end of the line makes it harder to miss control flow.
Style/IfUnlessModifier:
  Enabled: false

# This doesn’t always make sense.
Style/GuardClause:
  Enabled: false

# ----- ENABLED (new) -----

# These cops are new and need to be manually enabled.

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# ----- DISABLED (tests) -----

# These cops are disabled in test cases only.

Style/Documentation:
  Exclude:
    - "test/**/*.rb"

Style/GlobalVars:
  Exclude:
    - "test/**/*.rb"

Lint/NestedMethodDefinition:
  Exclude:
    - "test/**/*.rb"

# ----- DISABLED (metrics) -----

# Cops for metrics are disabled because they should not cause tests to fail.

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
